/* ============================================================
   Volledige foto-manifest — beide mappen
   - renovacija : map "renovacija objekta ikc din" (genummerd 1–28)
   - ikcdin     : map "Foto's ikc din" (eindbeelden + posters)
   Elk item: { id, title, folder }
   ============================================================ */
window.ALL_PHOTOS = [
  // ---- renovacija (de renovatie zelf) ----
  { id:'1bTvEAClMEcoiTIZOmBk6Tc3fdP_3FH5k', title:'1', folder:'renovacija' },
  { id:'1UOshy2i6ueNrXt4s-dqnBq2Md_3SORJJ', title:'2', folder:'renovacija' },
  { id:'1usLVhQ-QU-SC8vue1tyIZ8mZLOgERwr7', title:'3', folder:'renovacija' },
  { id:'13A4ag_M9fSOsx8zSh5CVK9Bo8sD3LWtd', title:'4', folder:'renovacija' },
  { id:'1WoLmWlI2SYU5EABeluxs90i0rx02bHNn', title:'5', folder:'renovacija' },
  { id:'1QDa9-BHrg7twPqKIr3Jk1ZGVUMvJy3ef', title:'6', folder:'renovacija' },
  { id:'128MG3FG6Woj-UScAirL92Rfg5wvpm7jk', title:'7', folder:'renovacija' },
  { id:'1owHbtYYVGnC8F5x0oNyByz9Shnv1uGh3', title:'8', folder:'renovacija' },
  { id:'1FMgMYbew3uXkWaVGE4Umu3ySIVZgzF6T', title:'9', folder:'renovacija' },
  { id:'1QXdusLbSka5NTbx-_7iFxbR5f8jIyDsf', title:'10', folder:'renovacija' },
  { id:'1ogHWAFZsTwIeWWGxsya95UI_mOCT-nLO', title:'11', folder:'renovacija' },
  { id:'1iOP6suNKvIcpFuNtAtkPQTMl_liISv3Q', title:'12', folder:'renovacija' },
  { id:'1CLZCwSZjn3em93-Z6RdWF2KkO37_9KXk', title:'13', folder:'renovacija' },
  { id:'1aEIgaqqYwgeWJFIZWz6TJZrGlwbrxnvc', title:'14', folder:'renovacija' },
  { id:'1E6fO-kkN0HGoPw72cF8QnzsMNfsNmCd4', title:'15', folder:'renovacija' },
  { id:'12W5OZQRlZ0XPyDebSJpCXRnhCDtJXFa8', title:'16', folder:'renovacija' },
  { id:'1UTbIWQspZzfMq3FlFUI2WoMAP7UDaBMo', title:'17', folder:'renovacija' },
  { id:'1cvmpFqfbOquyx4idc1hpE3FGoM8gnFBt', title:'18 (wow)', folder:'renovacija' },
  { id:'18awJLbkY4l773V6HEh72UbjLfNd4e0gC', title:'19', folder:'renovacija' },
  { id:'1ss_pZEvYvqV6Fm21VKgHZTlZouLuAEkB', title:'20 (zajedno jelo)', folder:'renovacija' },
  { id:'1S-mAjADl4RJFFjafI-ZBn2XTHN610LDE', title:'21', folder:'renovacija' },
  { id:'15ZMF-ZkoixV6CTmDFfhV_Xt4ipyxhsqd', title:'22', folder:'renovacija' },
  { id:'1Y3Lh5i2xe8Nu37Y6K6mO7xhgIsI2YS6G', title:'23', folder:'renovacija' },
  { id:'1uXkwMagikprAiW32AGlF0wLtU1JwBNbQ', title:'24', folder:'renovacija' },
  { id:'1ujpXCB_v401MxHIxJaatq1cLD5TeOEi1', title:'25', folder:'renovacija' },
  { id:'1PIZvdHeIkBQtinF4n_scc_a180e5gYop', title:'26', folder:'renovacija' },
  { id:'1vegSJShorsvvsyk_oS7wpUj8JmE0TrKS', title:'27', folder:'renovacija' },
  { id:'1C8kWYWozOLz-H7Y6TvROg4hD1QngPdy-', title:'28', folder:'renovacija' },

  // ---- Foto's ikc din (eindbeelden van het gebouw) ----
  { id:'1xaCuiPNVwSsqDMGb9NghEdH5gWTS7fo7', title:'ikc din džamija (high res)', folder:'ikcdin' },
  { id:'1agc10IznGtBOSR35rZ5dAsT8y_uT0Aoe', title:'džamija dark inside', folder:'ikcdin' },
  { id:'1r8CqqElvkDm9LNJLj2HAM41MUhg0z2Wr', title:'Daylight ikc din', folder:'ikcdin' },
  { id:'1bW_ghc6N7h9x5iMZ48_09VTbWP2ipT4H', title:'Nighttime prayer room', folder:'ikcdin' },
  { id:'1yBb_QPNDaERaanKFo5lFXAy7fp-z690l', title:'mihrab', folder:'ikcdin' },
  { id:'1RzRKWLxV30ggKUY48kX6KP1osNcVf7x4', title:'Podrum', folder:'ikcdin' },
  { id:'1lJKOapWjtmGslmKPb8qQRk5vh-ypfmra', title:'Divanhana', folder:'ikcdin' },
  { id:'1SHmKUqGFXLk3xuLgXJMgZYWMIEHbxqu2', title:'bosna u ikc din (divanhana)', folder:'ikcdin' },
  { id:'1mmNqxx-UOhQCSC6JUCzHXOrzUBLGvLVx', title:'culturele events divanhana', folder:'ikcdin' },
  { id:'1QEJBDRbkDqj9p7iM6RzyjUBthtA28ggh', title:'IMG_1186 (gevel)', folder:'ikcdin' },
  { id:'1zhKl_VA8h2q6K6WYJQ0aUat9q4VjfAbg', title:'IMG_9146', folder:'ikcdin' },
  { id:'1DPsQRTXQ4V5jDlD2tbNfX0p6g9HnOWNB', title:'IMG_9147', folder:'ikcdin' },
  { id:'1iugzS2nasWWFSISsrjkpprWRbR6Jk_VJ', title:'IMG_9148', folder:'ikcdin' },
  { id:'1_j8tZvmCzvvnilv8BKMVZj-sWCrqxWND', title:'IMG_9961', folder:'ikcdin' },
  { id:'1PGxsyjISKCvwVFKKCSMPTrSwQnIWy6g-', title:'IMG_9962', folder:'ikcdin' },
  { id:'1ztmmtIbcoWp8VCsGlNxA-eGMmN6syn5i', title:'IMG_9964', folder:'ikcdin' },
  { id:'1dY-kWwRM4PJND4mlnHr_DylIFGrXv1gJ', title:'IMG_9966', folder:'ikcdin' },
  { id:'1Vskh446YpiwK6Vd-IqvyBsmAmxWseipg', title:'IMG_9967', folder:'ikcdin' },
  { id:'1YHaYZ5blNhCs8kxtClWgEL4271E9lqbQ', title:'IMG_9971', folder:'ikcdin' },
  { id:'1MrSf_pNyO7ZMrGwpFuSfn6QkK1x3c21Z', title:'IMG_9972', folder:'ikcdin' },
  { id:'1X-3_3v0ODTlQb8rMftLIE7LdW3oHkNVW', title:'foto A', folder:'ikcdin' },
  { id:'1AnILoSF6NkBQVCUiYavCIGkZWhFX_Up8', title:'foto B', folder:'ikcdin' },
  { id:'1qcv6NULpz55NgnCKmp80k4t2WPpYDtZW', title:'foto C', folder:'ikcdin' },
  { id:'13pbxV5r3WWIlUpRYAIDJyZobTOFxU81P', title:'mekteb-01', folder:'ikcdin' },
  { id:'1w4GQVKCAjAmbMMppabmlHh0RVHXCxPdR', title:'mekteb-02', folder:'ikcdin' },
  { id:'1eSd_nD_Q2uvDsby7tN4ByPCMuhRcT89v', title:'mekteb-03', folder:'ikcdin' },
  { id:'1Z7YvzUVvjewhe59PaFMDw7F0ssShWTWw', title:'mekteb-05', folder:'ikcdin' },
  { id:'1l6dvJa2WlG6O7B6miWodwYrX9x_brhA3', title:'mekteb-06', folder:'ikcdin' },
  { id:'1JD0g6MA6JHiX5TeRSDYV6_q2TRZI9Ue4', title:'mekteb-07', folder:'ikcdin' },
  { id:'1lWjrp1lUElAhpVWBEeMCJiB3b8G9ac1Q', title:'mekteb-08', folder:'ikcdin' },
  { id:'1z3PknoniEOTUjASoKcCm2QEkUWhW178M', title:'mekteb-09', folder:'ikcdin' },
  { id:'1X50wyzfJVCIkglue1V6yIA2xLejpqN9v', title:'mekteb-10', folder:'ikcdin' },
  { id:'1hNG00ERT2winqtJ5rr_G1_Zwz6GnyUwP', title:'mekteb-11', folder:'ikcdin' },
  { id:'1_V3c9sNGIJKViT_cd87mwE0AQLcZG0w1', title:'mekteb-13', folder:'ikcdin' },
  { id:'1hYISAJ_uORkTHTXu4d1jP44O72TtAWkH', title:'mekteb turnir', folder:'ikcdin' },
  { id:'1uBE7NhokniGq3qDc1S99SLYZPlunF2Wv', title:'kafa bosanska', folder:'ikcdin' },
  { id:'1O0s2iKwUF2pQGAo-4PfML_RSv9FyebfN', title:'koran les 2', folder:'ikcdin' },
  { id:'1ycpe7is6C66TJ7fxiuOd0HU9p67Y4Ypi', title:'koran lessen', folder:'ikcdin' },
  { id:'1YrfLlmjpgtqqxwk9HTiwIhXbNMfjqFeg', title:'kaligrafija', folder:'ikcdin' },
  { id:'1NZIORQSB-6Nr4S4pECTIB9AYeLvLeNiZ', title:'kaligrafija bijeenkomst', folder:'ikcdin' },
  { id:'132Etgb1KAwUxv4IL7xCtmF6Gfr2W9cbx', title:'umjetnost izložba', folder:'ikcdin' },
  { id:'13QXebQybqedHRf7NTXeO4bna-1kch2PU', title:'bošnjaštvo', folder:'ikcdin' },
  { id:'1motf5vaFvSDJtAEGg3aM62wiQZh0cpwr', title:'dani tradicije', folder:'ikcdin' },
  { id:'11UKfJ3b1gTbJrAc2lOdn2A1lUyySBDKQ', title:'predavanja', folder:'ikcdin' },
  { id:'16z0xdPegYTeOVG0FRvmvjFsZOZBM5OmC', title:'večer duhovnosti', folder:'ikcdin' },
  { id:'10VTNLKqJVQaqW2lg0h0Yo1qHnfEKZwPw', title:'vjenčanje', folder:'ikcdin' },
  { id:'1ZveuDcG4O0A26biDZYogzJ3D3aQj8Dj4', title:'srebrenica u ikc din', folder:'ikcdin' },
  { id:'1oYl-3ck6qPvTC_XSVy7zwEkyK0E43Imi', title:'irfo srebrenica', folder:'ikcdin' },
  { id:'1g0JqsQNWwVaxcCKqxR-GaL4Bi_DSUrUd', title:'fuča', folder:'ikcdin' },
];

window.photoSrc = function(id, w){
  w = w || 700;
  return 'https://drive.google.com/thumbnail?id=' + id + '&sz=w' + w;
};
